"""Add avatar_public_id field to photographers

Revision ID: 1bc57ea0d894
Revises: b2e7faa01e26
Create Date: 2025-03-19 03:05:26.760239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc57ea0d894'
down_revision = 'b2e7faa01e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_public_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographers', schema=None) as batch_op:
        batch_op.drop_column('avatar_public_id')

    # ### end Alembic commands ###
