"""Добавлены поля avatar и avatar_public_id в модель Client

Revision ID: 67e708435b12
Revises: 7a296b446963
Create Date: 2025-03-24 23:54:50.736473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e708435b12'
down_revision = '7a296b446963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_public_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('avatar_public_id')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
