"""Add telegram_id field to photographers

Revision ID: 7a296b446963
Revises: 1bc57ea0d894
Create Date: 2025-03-19 03:32:22.453693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a296b446963'
down_revision = '1bc57ea0d894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographers', schema=None) as batch_op:
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
