"""Добавлено поле country в модель Client

Revision ID: b2e7faa01e26
Revises: 9f05bb37e316
Create Date: 2025-03-16 13:54:20.925694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e7faa01e26'
down_revision = '9f05bb37e316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
